#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

import:
  common: common-properties.yaml

Kubesec:
  Product: '${common.helm-chart-name}' #Node/TPG Name (Mandatory Parameter) Eg. "cha" or "eric-bss-cha-access"
  Product_internal: '${common.helm-chart-name}' #Product name (this is an optional parameter) Eg. "cha-access"
  Product_contact: 'me@ericsson.com' #Email of the SPOC or DL (Mandatory Parameter)
  KubesecYAML:
    Scan: True
    armLinks:
      Links:
      valuesOverride:
    armLinksWithAuth:
      Links:
      armUser: ''  # Mandatory if links given
      armEncryptedPwd: ''  # Mandatory if links given
      valuesOverride: # If override is needed, add the values yaml names in the same order as arm links, if none, mark it ''
          - ''
  KubesecCluster:
    Scan: False
    KubeconfigFile: "admin.conf"
    namespace: ''